### ISSUE TITLE
Negative or overflowed "net money/click" value

### ISSUE THREAD

**Issue by mattpep** [gzgreg/DerivativeClicker#12]
My save game is in the gist https://gist.github.com/mattpep/aed0dd7a903bd86a9426
I had the game running in the background; some time over the past half day or so the "net money/click" metric went negative (presumably via an overflow) and as a result the money value has dropped to zero.

When the autoclick triggers I get a momentary injection of money but that disappears by the next tick.
Manually clicking to gain more money also has the same effect; money comes in, but it's going out too quickly to be used.

I've not found anything in the game which consumes money, other than manual purchases. Is there anything I can do to recover from this near-zero balance situation?

**Comment by gzgreg** [comment]
Proofs cost money (more precisely, 5$ each)! Looks like your proof production's outstripped your money production.
