### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by LilLegendGamerez** [gzgreg/DerivativeClicker#18]
Starts taking away money at one point 
![Screenshot 2023-01-11 2 01 41 PM](https://user-images.githubusercontent.com/118675655/212141902-53d02610-9c27-4f95-a033-c0e9f84fafa8.png)

**Comment by SpiderScripts** [comment]
This is a feature, not a bug.
You have more proof generation than income generation.
This will resolve itself over time by buying more from the computer branch to turn those proofs into income.
